### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by khanhtoan529** [jparkerweb/rich-foot#1]
I have already toogle on plugin, but not showing anything in the note editor.

**Comment by YMHJERUSALEM** [comment]
SAME

**Comment by jparkerweb** [comment]
if toggled on, you should at least see the created / modified date.
please note that this will only be displayed in "reading mode".
if you open your Obsidian dev console do you have any errors there? (ctrl + shift + i)

**Comment by khanhtoan529** [comment]
> please note that this will only be displayed in "reading mode".

Please mention this in the README

**Comment by jparkerweb** [comment]
will do, also I will investigate getting it to render in "preview mode" as well

**Comment by jparkerweb** [comment]
@khanhtoan529 @YMHJERUSALEM 
I have just updated the plugin to support both `live preview` and `editing` modes.
please let me know if you run into any other issues after updating the plugin in Obsidian.

thanks!

**Comment by jparkerweb** [comment]
example:
![image](https://github.com/user-attachments/assets/c304ed60-e192-45ae-9002-25ccb390c90b)

**Comment by YMHJERUSALEM** [comment]
@jparkerweb man its wonderfull!
big like!
