### ISSUE TITLE
🖇️ Show Transcluded Outlinks

### ISSUE THREAD

**Issue by stoweboyd** [jparkerweb/rich-foot#14]
I use transclusions quite a bit. In a daily note I will reference a note, and select a paragraph or a section, like this

`![[some other note#some section]]`

However, these outlinks don't appear in the outlinks of Rich Footer.

**Comment by jcesguerram** [comment]
Second this! It would be a fantastic feature to add

**Comment by jparkerweb** [comment]
Thanks for the feature request. I'll look into this 🦶

**Comment by jparkerweb** [comment]
Update the plugin in Obsidian!!!

**Comment by jparkerweb** [comment]
@stoweboyd @jcesguerram 
working ok?

**Comment by jcesguerram** [comment]
> @stoweboyd @jcesguerram Update the plugin in Obsidian 💎 The feature is now live, let me know if you have any other questions or feature requests :)

yeah, it's working great! thanks!

**Comment by stoweboyd** [comment]
It's now working for transclusions! (Although I am raising another issue with outlinks in footnotes...)
