### ISSUE TITLE
Version 1.5.11 is unable to display the backlink

### ISSUE THREAD

**Issue by junkfood-pi** [jparkerweb/rich-foot#18]
Version 1.5.11 is unable to display the backlink

**Comment by jparkerweb** [comment]
@junkfood-pi please update to the latest version in Obsidian and reopen an issue if still a problem.
As with all software, older versions may have bugs ;)

**Comment by junkfood-pi** [comment]
At the bottom of the page, there are only outlinks, but this article does have backlinks

**Comment by jparkerweb** [comment]
Have you updated to the latest version?
Are backlinks enabled settings?
Can you share an example note or create an example vault so I can validate/use to address this?
