### ISSUE TITLE
✅ Diff date format when only have 1 property

### ISSUE THREAD

**Issue by np6390** [jparkerweb/rich-foot#19]
Example when I only have created field in property: then the format between created date and modified date can't be control

![image](https://github.com/user-attachments/assets/6f8e54df-17ae-4d53-a61e-dacc876fd547)

**Comment by jparkerweb** [comment]
@np6390 
yeah, I am using the string value of the custom field for display.
I might be able to test if the string can be converted to a date and display it in the `formatted` way.
Let me look into it...

**Comment by jparkerweb** [comment]
@np6390 
please update the plugin in Obsidian.
Latest patch release should resolve the issue and allow you to use either a custom string or date :)
