### ISSUE TITLE
🫣 Page Preview Support for Outlinks/Backlinks

### ISSUE THREAD

**Issue by Moyf** [jparkerweb/rich-foot#21]
Could you please consider changing the links of Outlinks/backlinks into Obsidian's "internal link", so that some basic functions (like mouse hover link to preview) could be triggered?

https://github.com/user-attachments/assets/fbe15f1b-5b7a-4225-83a4-d64cdde7a876

**Comment by Moyf** [comment]
I also tried this [feature](https://github.com/Moyf/rich-foot/commits/improve-links), but it is not working on my end, and I'm not sure why.

**Comment by ksdavidc** [comment]
me too! And not to forget link to headings and blocks and also link display text! This would just awesome!

**Comment by jparkerweb** [comment]
@Moyf @ksdavidc 
![Image](https://github.com/user-attachments/assets/11b50413-0f2a-4f48-ad5c-792ba4e7484c)
Update the plugin in Obsidian 🎉

**Comment by jparkerweb** [comment]
https://github.com/jparkerweb/rich-foot/releases/tag/1.8.0
