### ISSUE TITLE
🐛 Plugin causes tables in Canvas not to render

### ISSUE THREAD

**Issue by Morganwan90** [jparkerweb/rich-foot#23]
When using Obsidian Canvas with embedded notes containing tables, the tables fail to render properly if this plugin is enabled. The tables render correctly after disabling the plugin.

## Steps to Reproduce
1. Create a note with a table
2. Embed this note into a Canvas
3. Enable the plugin
4. Open the Canvas

**Comment by jparkerweb** [comment]
@Morganwan90 
Please update the plugin in Obsidian.
Latest patch release should resolve the `css` issues you observed while in Canvas mode (please note that rich-foot is currently not rendered in Canvas, but may be in the future).
