### ISSUE TITLE
🥙 Combine Backlinks/Outlinks and Indicate Direction with Arrow

### ISSUE THREAD

**Issue by formerCIAjanitor** [jparkerweb/rich-foot#25]
Thanks for the nice plugin.
I would welcome an option to have backlinks and outlinks displayed together.

So instead of having

```
BACKLINKS 
<--link1   <--link2   <--link3

OUTLINKS
<--link2   <--link4
```

I am suggesting
```
<--link1   <--link3   <--link2-->   link4-->
```
Link direction is indicated with the arrow. Backlinks are displayed first.  
This saves vertical space.

Thank you for considering this!

**Comment by jparkerweb** [comment]
![Image](https://github.com/user-attachments/assets/bdeee57c-4da7-4ce0-b79f-7fddf39ae260)

**Comment by jparkerweb** [comment]
https://github.com/jparkerweb/rich-foot/releases/tag/1.9.0

![Image](https://github.com/user-attachments/assets/d4919317-6ff7-4a77-8a19-354b72f3b549)

**Comment by formerCIAjanitor** [comment]
Thank you for implementing this right away!

**Comment by jparkerweb** [comment]
Thanks for the idea!
your always welcome to support me on ko-fi ;)

# [☕ ko-fi](https://ko-fi.com/jparkerweb)

NEVER expected, ALWAYS appreciated!
