### ISSUE TITLE
🐛  Date not Formatted Correctly if Timestamp Included

### ISSUE THREAD

**Issue by Moyf** [jparkerweb/rich-foot#26]
Obsidian's default date time format is [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601)
For instance: `2024-11-28T21:52:00`
![image](https://github.com/user-attachments/assets/9568fa01-a298-4bbf-82be-d37a0986e138)
*Created in Sandbox Vault*

There is a `T` between date and time.

And the [new code](https://github.com/jparkerweb/rich-foot/commit/c665630adb976accf85ee740d0c543bd8d79aa3c#diff-27653c212e1cfe533e4eb2f7d0d3f89604c9de48a09583b4cbbbcbd08a07da79R395) used `modifiedDate.split('-').map(Number);`, it will cause this issue:
My datetime properties is below, and it cannot be parsed.
![image](https://github.com/user-attachments/assets/93e30d3e-4696-441d-9a26-1624f32d54f4)

And I'll get `Nah` in the dates:
![image](https://github.com/user-attachments/assets/3636ee9f-50a9-48e8-9117-3fa84d6908c1)

> In addition, I'm afraid the map of Months couldn't be translated into different Languages.

**Comment by jparkerweb** [comment]
Thanks @Moyf ,
I will update the code to account for this use case.
I only tested using the `date` property type in frontmatter fields and didn't think you would be manually entering date + time

**Comment by Moyf** [comment]
> Thanks @Moyf , I will update the code to account for this use case. I only tested using the `date` property type in frontmatter fields and didn't think you would be manually entering date + time
> 
> It probably will go out tomorrow since today is a US holiday, but I might be able to squeeze it in (no promises). ;)

Oh, of course! There's no rush at all. Take your time and enjoy your holiday!! 🥳
Happy Thanksgiving Day!

> And thank you for giving us those amazing plugins 🥺

---

Actually I usually don't enter the date-time manually. Instead, I use **Templater** pugin to add the `created date` and **Update Time Updater** to update the `modified date` in a specific format  ; )
