### ISSUE TITLE
[bug/improvement] Backlinks list shouldn't include the current file

### ISSUE THREAD

**Issue by vforge** [jparkerweb/rich-foot#3]
Great plugin! I have one issue with it though:

Steps to reproduce:

1. Create any file.
2. Put a link that points to the file itself.
3. Backlinks have a link to the same file, clicking on it does nothing.

There should either be an option to hide it (ideally), or this non-working link can be removed from the backlinks list, as putting links to note itself in H1 is a pattern that people use, as this allows to sync in-file H1 title with note title automatically.

**Comment by jparkerweb** [comment]
Thanks for the suggestion.
This has been fixed in version [1.2.0](https://github.com/jparkerweb/rich-foot/releases/tag/1.2.0)
