### ISSUE TITLE
❓ Incompatibly between richfooter and ITS theme

### ISSUE THREAD

**Issue by Konijnebeer** [jparkerweb/rich-foot#31]
Hi I installed richfooter to replace my dataview tables that show backlinks to a file but noticed a bug:
Without richfooter the text can easily fit next to the ITS theme callout like this:
![image](https://github.com/user-attachments/assets/022633ae-1f20-4fb2-992b-83840cd0681d)
But with richfooter enabled it pushes everything bellow the callout:
![image](https://github.com/user-attachments/assets/24cc040b-2a54-4e15-8d01-25b222176b40)
I'm unsure what could cause this, I also have pixelbanner enabled as shown but disabling that does not seem to change the issue
(The screenshots are both taken in reading view)

**Comment by jparkerweb** [comment]
@Konijnebeer 
I will need the "source" of an example note or an example vault to see what the issue is.
Please provide one, thank you!

**Comment by Konijnebeer** [comment]
Oh sorry my bad
```
>[!infobox]
> # Name
> ![[Image.png|cover small]]
> ###### Info
> | Type |  -- |
> | ---- | ---- |
> | Location | x |
> | Class | x |
> | Race | x |
> | Deity | x |
> | Gender| x |
> | Age | x |
> | Birth | x |
> | Death | x |
> | Height | x M|


### Relations


### Personality & Looks

#### Misinformation/Lies
```
Can't seem to upload a file and the vault is not published but just putting this in a notes with ITS theme enabled and richfooter, should work

**Comment by jparkerweb** [comment]
holy crap, what a pain in the ass, but I think I have a solution:
![Image](https://github.com/user-attachments/assets/8d14445c-6796-41bd-93bd-00233705a8b9)

**Comment by jparkerweb** [comment]
@Konijnebeer 

Fix now live, please update `rich-foot` plugin in Obsidian:
https://github.com/jparkerweb/rich-foot/releases/tag/1.9.2

thank you!

### [1.9.2] - 2024-12-01
#### 🐛 Fixed
- dynamic `css` in `reading` mode disrupting document flow of floated elements (e.g. ITS callouts)
- debounced `updateRichFoot` in `editing` mode (new settings option that allows delay in milliseconds)
