### ISSUE TITLE
🐛 Outlinks in Footnotes Not Showing in Rich Foot

### ISSUE THREAD

**Issue by stoweboyd** [jparkerweb/rich-foot#32]
I use footnotes quite a lot (particulalrly because of TfTHacker's Cornell Notes/Sidenotes system). But a construction like this --

`some text^[ more text [[reference to another note]].]`

-- does not lead to the `reference to other note` showing in the rich footer.

![outlink in footnote](https://github.com/user-attachments/assets/4a1d1c6e-e6fb-4776-a0db-a9db296de631)

The references to `Lewis Mumford` and `2024-11-30 quote - Lewis Mumford - the city of the dead` don't show up in this note's rich footer, but they do if I place them outside of the footnote

**Comment by jparkerweb** [comment]
![Image](https://github.com/user-attachments/assets/c98a136c-f527-4d87-a33c-1ea52f2bf954)

**Comment by jparkerweb** [comment]
https://github.com/jparkerweb/rich-foot/releases/tag/1.9.0

**Comment by stoweboyd** [comment]
Great! Thanks a lot.
