### ISSUE TITLE
🐛 Links from Frontmatter not Dissplayed in Rich-Foot

### ISSUE THREAD

**Issue by davidszp** [jparkerweb/rich-foot#34]
Putting the following links in the body of the .md document displays the outgoing links as expected by rich-foot:
```
  - "[[Corporate Lifecyle and Return on Capital]]"
  - "[[Gillette and the longevity of moats]]"
```

However, moving these links to frontmatter does not work for me, they simply do not get displayed at all.

```
---
links:
  - "[[Corporate Lifecyle and Return on Capital]]"
  - "[[Gillette and the longevity of moats]]"
modified: 2024-12-01
---
```

I was expecting the behavior to be identical between links in the body or frontmatter of the document.

**Comment by jparkerweb** [comment]
Interesting, I'll take a look.
Thanks for the issue submission.

**Comment by jparkerweb** [comment]
@davidszp 
should be fixed now, please update the plugin in Obsidian:
https://github.com/jparkerweb/rich-foot/releases/tag/1.9.1

**Comment by davidszp** [comment]
Thank you, just tried and works fine now with 1.9.1.
