### ISSUE TITLE
‼️ Conflict with Hover Editor Plugin

### ISSUE THREAD

**Issue by ksdavidc** [jparkerweb/rich-foot#36]
Enabling both leads to flickering and occasional inability to get the hover. I tried adjusting some of the settings and delays, but with little success. setting default hover editor mode to "current file" seemed to help a little.

https://github.com/user-attachments/assets/9340f945-98f5-4cf8-87e9-a45052083bbb

https://github.com/user-attachments/assets/2e783eb3-7b55-4dd0-b2ea-dc26397b0a1d

**Comment by jparkerweb** [comment]
@ksdavidc 
This is a tough one, as Obsidian uses a `Shadow DOM` to control its content, its not trivial to prevent rich-foot from being removed when the hover editor popover is being initiated.

Will need time to rethink/work this one out.
Would love some help 🤣 as `rich-foot` isn't the only project I'm working on.

**Comment by ksdavidc** [comment]
sorrry to have been the bearer of bad tidings. It's way out of my league, but someday I guess. For now I will use one or the other, depending on the vault.

**Comment by jparkerweb** [comment]
@ksdavidc thank you again for reporting the conflict with Hover Editor.
we will get it fixed, just not an easy one at the moment.

I'll ping you back here when something is deployed addressing it.
In the meantime we did just have to release today (rich foot & pixel banner)

https://github.com/jparkerweb/pixel-banner/releases/tag/2.12.0
https://github.com/jparkerweb/rich-foot/releases/tag/1.9.2

**Comment by ksdavidc** [comment]
no worries, low priority. Hover seems a bit in the weeds with issues and also "leverages Obsidian functionality that is not currently exposed in the official API.", so you may have your work cut out for you.

**Comment by pjeby** [comment]
@jparkerweb if you have any questions for me on how Hover Editor works or need something changed in it, leave a comment on the [HE ticket for this](https://github.com/nothingislost/obsidian-hover-editor/issues/295) and I'll see what I can do.

**Comment by jparkerweb** [comment]
@pjeby likewise.

I'm not planning on changing the current implementation of `rich-foot` as it already works with the core plugin hover "preview" notes, etc.

I haven't had time to dig into the `hover edit` implementation, but based on the comments, it seems the preferred API's from Obsidian might not be available at this time.

good luck to you.

**Comment by ksdavidc** [comment]
Guys (or other pronouns), I am so happy it looks like a resolution has been found! Thank you so much for the fine teamwork!! Fixing this helped me find a few other errors along the way, but having a real solution to the original problem is the icing on the cake! Thank you!

**Comment by ksdavidc** [comment]
I copied over the changes in the commit to my vault, and it works well,...

_though_...I noticed something: when the hover edit window closes, there is another autoscroll/flicker up that happens:

https://github.com/user-attachments/assets/6c9014af-a4b9-45b1-a8c0-212efb7e3a6f

Would there be any way to eliminate that, so the rich foot stays visible?

**Comment by jparkerweb** [comment]
@ksdavidc @pjeby I am reopening this issue while I explore a possible official fix here to the plugin.

**Comment by jparkerweb** [comment]
@pjeby thanks for looking into this further.  This is exactly what I am exploring. I unfortunately need to be fairly aggressive with reinserting `rich-foot` to counter the various DOM cleanup/manipulation that Obsidian does while scrolling, etc.  I final solution will involve cache and comparison/updates for certain events.

**Comment by ksdavidc** [comment]
@pjeby @jparkerweb I am feeling sorry that I opened a can of worms :-( , I will say that even this temporary/partial fix is much better than it was before. I understand that this will be a challenge and will take time to address properly, but both plugins are invaluable for me in my daily workflow. So, I really appreciate the time, thought, and effort you have put in on it even this far. At least now it doesn't feel totally broken and there is hope for an elegant solution eventually.
