### ISSUE TITLE
🐛 Editing Notes Causing rich-foot to Update without a `debounce`

### ISSUE THREAD

**Issue by davidszp** [jparkerweb/rich-foot#37]
How to recreate:
- disable all plugins except for richfoot
- disabled all css snippets, using default theme
- load a longer markdown document (> 1 page)
- type at the bottom of the document

![2024-12-02_09-19-05](https://github.com/user-attachments/assets/d670f655-4d55-4927-9463-d343a9bfefb2)

**Comment by jparkerweb** [comment]
fix on the way, thank you!
![image](https://github.com/user-attachments/assets/6de3291d-7e4d-4595-a72a-fac5f8e439f4)

**Comment by jparkerweb** [comment]
Fix now live, please update `rich-foot` plugin in Obsidian:
https://github.com/jparkerweb/rich-foot/releases/tag/1.9.2

thank you!

### [1.9.2] - 2024-12-01
#### 🐛 Fixed
- dynamic `css` in `reading` mode disrupting document flow of floated elements (e.g. ITS callouts)
- debounced `updateRichFoot` in `editing` mode (new settings option that allows delay in milliseconds)
