### ISSUE TITLE
Flickers when editing note

### ISSUE THREAD

**Issue by kmaustral** [jparkerweb/rich-foot#40]
I find that the note flickers when it is being edited and the Rich Foot plugin is enabled. I suspect that it is being refreshed to update on any changes to the links. I had to disable the plugin to continue working. Would it be possible to refresh only when opening the note? Or to have this as an option?

**Comment by jparkerweb** [comment]
Please make sure you update `rich-foot` to the latest version:
https://github.com/jparkerweb/rich-foot/releases/tag/1.9.2

I added a update delay option to settings to address this:
- debounced updateRichFoot in editing mode (new settings option that allows delay in milliseconds)

If you are still having an issue please let me know.
Thanks

![image](https://github.com/user-attachments/assets/6eab647b-f75a-4864-a9b0-5de65b4ca64f)
