### ISSUE TITLE
Conflict with thino plug-in

### ISSUE THREAD

**Issue by lxmwwl** [jparkerweb/rich-foot#42]
![image](https://github.com/user-attachments/assets/29023f6f-173d-43ec-b60e-d562d3c5be7c)

**Comment by jparkerweb** [comment]
What is the conflict?
from the screenshot it looks like it is working fine.

**Comment by lxmwwl** [comment]
> What is the conflict? from the screenshot it looks like it is working fine.

This is just an input box
![image](https://github.com/user-attachments/assets/372e8636-a0a6-48a6-83f1-df55b340a595)

**Comment by jparkerweb** [comment]
@lxmwwl 

![image](https://github.com/user-attachments/assets/4877e642-842e-4294-a416-635616282c32)

Can you please upload a sample vault here (create a .zip file) so I can see the issue.

**Comment by lxmwwl** [comment]
> @lxmwwl
>
> ![image](https://private-user-images.githubusercontent.com/3073864/393533808-4877e642-842e-4294-a4 16-635616282c32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoic mF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2Mjg1MjcsIm5iZiI6MTczMzYyODIyNyw icGF0aCI6Ii8zMDczODY0LzM5MzUzMzgwOC00ODc3ZTY0Mi04NDJlLTQyOTQtYTQxNi02MzU2MTYyODJjMzIucG5nP1gtQW16LU FsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIw OCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDhUMDMyMzQ3WiZYLUFtei1FeHBpcm VzPTMwMCZYLUFtei1TaWduYXR1cmU9OTBkZjZjZWVkNTlkMWUwYjYwZTg0MmQ0MTQ3MmZiZTAzZDcxZjM3YTAxM2Y1OTQ4NmFh OTgxYjUzM2NlZGI2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ANb66hPMPE5_LV9Ld-1SuTYr1JuyJ6Cccwh6Uva7pxE)
>
> Can you please upload a sample vault here (create a .zip file) so I can see the issue.

![image](https://github.com/user-attachments/assets/67804857-05c8-4ef3-b809-c81ea535adf5)
![image](https://github.com/user-attachments/assets/c1611947-1535-4f76-9ebc-07d7f9cffee5)
in this place

**Comment by lxmwwl** [comment]
> @lxmwwl
> 
> ![image](https://private-user-images.githubusercontent.com/3073864/393533808-4877e642-842e-4294-a416-635616282c32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2Mjg1MjcsIm5iZiI6MTczMzYyODIyNywicGF0aCI6Ii8zMDczODY0LzM5MzUzMzgwOC00ODc3ZTY0Mi04NDJlLTQyOTQtYTQxNi02MzU2MTYyODJjMzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDhUMDMyMzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTBkZjZjZWVkNTlkMWUwYjYwZTg0MmQ0MTQ3MmZiZTAzZDcxZjM3YTAxM2Y1OTQ4NmFhOTgxYjUzM2NlZGI2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ANb66hPMPE5_LV9Ld-1SuTYr1JuyJ6Cccwh6Uva7pxE)
> 
> Can you please upload a sample vault here (create a .zip file) so I can see the issue.

![image](https://github.com/user-attachments/assets/afa88beb-3b27-4fed-9bf8-e6be17563ee5)
in this place
![image](https://github.com/user-attachments/assets/292c2de9-2806-47bf-936f-e6c5de6a2fb0)

**Comment by lxmwwl** [comment]
[test.zip](https://github.com/user-attachments/files/18050642/test.zip)

**Comment by jparkerweb** [comment]
thank you. I'm creating a new Exclusion section in settings to allow users to exclude rich foot from certain hierarchy elements in the DOM:
![image](https://github.com/user-attachments/assets/5c517aac-8243-4371-9abd-a89831dce289)

**Comment by jparkerweb** [comment]
@lxmwwl upgrade to the latest release and add `[data-type="thino_view"]` to the new "Excluded Parent Selectors" settings section 👍

let me know if you have any more issues.
[test-fixed.zip](https://github.com/user-attachments/files/18056535/test-fixed.zip)

**Comment by jparkerweb** [comment]
# v1.10.0 - 🛑 Exclude Me Please

## What's New 🎉

### v1.10.0
### ✨ Added
- Exclusion rule via `frontmatter` field
- Custom exclusions using specified DOM parent selectors for advanced control

![v1.10.0](https://raw.githubusercontent.com/jparkerweb/ref/refs/heads/main/equill-labs/rich-foot/rich-foot-v1.10.0.jpg)

---

Please consider sending me a tip to support my work 😀
# 🍵 [tip me here](https://ko-fi.com/jparkerweb)
⇢ 💻 Visit [eQuill Labs](https://www.quilllabs.com)
⇢ 💬 Join the [Discord](https://discord.gg/sp8AQQhMJ7)

**Comment by lxmwwl** [comment]
> https://github.com/jparkerweb/rich-foot/releases/tag/1.10.0
>
> # v1.10.0 - 🛑 Exclude Me Please
> ## What's New 🎉
> ### v1.10.0
> ### ✨ Added
> * Exclusion rule via `frontmatter` field
> * Custom exclusions using specified DOM parent selectors for advanced control
>
> ![v1.10.0](https://raw.githubusercontent.com/jparkerweb/ref/refs/heads/main/equill-labs/rich-foot/rich-foot-v1.10.0.jpg)
>
> Please consider sending me a tip to support my work 😀
>
> # 🍵 [tip me here](https://ko-fi.com/jparkerweb)
> ⇢ 💻 Visit [eQuill Labs](https://www.quilllabs.com) ⇢ 💬 Join the [Discord](https://discord.gg/sp8AQQhMJ7)

Thank you, can you give me a support link that can be used in China? For some reasons, I cannot use payment software outside China.
