### ISSUE TITLE
🐛 Extra Padding in Canvas and Kanban Cards

### ISSUE THREAD

**Issue by lxmwwl** [jparkerweb/rich-foot#44]
![image](https://github.com/user-attachments/assets/b16b2975-e201-4f50-bc04-b1373b0100c1)
There is an extra blank space below that cannot be entered.

**Comment by lxmwwl** [comment]
> ![image](https://private-user-images.githubusercontent.com/124525616/394239767-b16b2975-e201-4f50-bc04-b1373b0100c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MjgwNDMsIm5iZiI6MTczMzgyNzc0MywicGF0aCI6Ii8xMjQ1MjU2MTYvMzk0MjM5NzY3LWIxNmIyOTc1LWUyMDEtNGY1MC1iYzA0LWIxMzczYjAxMDBjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQxMDQ5MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjk5Mjk5YjJlMGJiNzM4YjI4MGE4N2UyOTNkYTQ0NWZmODFmZDVhMmIzMTE0Mjc1NDk4ZDM2OTVjZjU3ZWIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.J6j0wpjhqPg8ZE9oqJDJuHL4-FYmxTgsuAiVeD_AtYM) There is an extra blank space below that cannot be entered.

This situation also occurs with the kanban plug-in
![image](https://github.com/user-attachments/assets/1a0ffd61-4fd0-4f20-959b-541c6c80b568)

**Comment by jparkerweb** [comment]
@lxmwwl this should be fixed now. Please update the plugin in Obsidian:
https://github.com/jparkerweb/rich-foot/releases/tag/1.10.1
