### ISSUE TITLE
🐛 Missing "Excluded Folders" control in Settings

### ISSUE THREAD

**Issue by chenghuang-coder** [jparkerweb/rich-foot#46]
hey,

first of all thank u 4 this great plugin!

I'm working on a chinese version of doc, current version is 1.10.1, then I find that the empty space which are designed to fill in the folder path is missing, plz consider to fix this in the next release
![f844d4c8-0983-48c0-b5d6-8278a2ab3e02](https://github.com/user-attachments/assets/f4356143-64e8-4f95-a935-5aa53f80b473)

one more problem: plz consider to make clear in the setting about how to divide multiple values, by "," and a space, maybe?

best wishes

**Comment by jparkerweb** [comment]
@chenghuang-coder,
Thank you for reporting this.

The missing control should be restored now if you update to the latest version:
https://github.com/jparkerweb/rich-foot/releases/tag/1.10.2
