### ISSUE TITLE
Hello author, may I ask how to exclude this place?

### ISSUE THREAD

**Issue by lxmwwl** [jparkerweb/rich-foot#49]
![image](https://github.com/user-attachments/assets/5ddff688-1bce-47e0-b831-3e4515b5a013)

**Comment by jparkerweb** [comment]
please try this and let me know if it doesn't work:
`[data-type="thino_view"]`

![393573493-5c517aac-8243-4371-9abd-a89831dce289](https://github.com/user-attachments/assets/533cc087-4767-4035-86b1-0698b34f08c3)

**Comment by lxmwwl** [comment]
> please try this and let me know if it doesn't work:请尝试此操作，如果不起作用请告诉我： `[data-type="thino_view"]`
> 
> ![393573493-5c517aac-8243-4371-9abd-a89831dce289](https://private-user-images.githubusercontent.com/3073864/395687182-533cc087-4767-4035-86b1-0698b34f08c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxNjQyNzIsIm5iZiI6MTczNDE2Mzk3MiwicGF0aCI6Ii8zMDczODY0LzM5NTY4NzE4Mi01MzNjYzA4Ny00NzY3LTQwMzUtODZiMS0wNjk4YjM0ZjA4YzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTRUMDgxMjUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWU4N2M3NGVkMGRlMTVhMjU4ZjU5OTg4NTg5MTMxOGE5MjVkY2NlMjcwYWRjNzk2ODVmYzUxY2I1ZDM0MjNkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.f3CBz-QEY2St6dUt8bifhQu1j2S2BEYr55F4mVexlwk)

I tried this operation, but found that it does not work for the thino interface in this new window

**Comment by lxmwwl** [comment]
> please try this and let me know if it doesn't work: `[data-type="thino_view"]`
> 
> ![393573493-5c517aac-8243-4371-9abd-a89831dce289](https://private-user-images.githubusercontent.com/3073864/395687182-533cc087-4767-4035-86b1-0698b34f08c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxNjQyNzIsIm5iZiI6MTczNDE2Mzk3MiwicGF0aCI6Ii8zMDczODY0LzM5NTY4NzE4Mi01MzNjYzA4Ny00NzY3LTQwMzUtODZiMS0wNjk4YjM0ZjA4YzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTRUMDgxMjUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWU4N2M3NGVkMGRlMTVhMjU4ZjU5OTg4NTg5MTMxOGE5MjVkY2NlMjcwYWRjNzk2ODVmYzUxY2I1ZDM0MjNkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.f3CBz-QEY2St6dUt8bifhQu1j2S2BEYr55F4mVexlwk)

I tried this operation, but found that it does not work for the thino interface in this new window

**Comment by jparkerweb** [comment]
@lxmwwl Please update the plugin and try again:
https://github.com/jparkerweb/rich-foot/releases/tag/1.10.3

**Comment by lxmwwl** [comment]
> @lxmwwl Please update the plugin and try again: https://github.com/jparkerweb/rich-foot/releases/tag/1.10.3

Thank you very much
