### ISSUE TITLE
Filter by file Extension

### ISSUE THREAD

**Issue by robsonkx** [jparkerweb/rich-foot#6]
It would be great if you could add exception filter by file extension. For example, it would be good to hide images and display relevant files only in the foot note.

**Comment by jparkerweb** [comment]
@robsonkx can you please expand on this idea with some specific examples?
I'm not sure I understand what you are asking.

Thanks!

**Comment by robsonkx** [comment]
Hi

I mean, there is a option to insert path exception in the configuration and
I suggest create another same option but to insert file name exception. for
example

*.png


the foot will not show images

**Comment by jparkerweb** [comment]
For now I am filtering out all non-note files from the backlink section (you will only see links to .md files)
