### ISSUE TITLE
Add to footer in Live Preview Mode

### ISSUE THREAD

**Issue by Kullenej** [jparkerweb/rich-foot#7]
Thank you for an amazing plugin!

I have one issue: when I'm writing my notes in Live Preview the dates and backlinks are in the right side of the document and not in the footer. Not until I turn to reading mode does it go down to the footer (see the two pictures attached). Is this on purpose or something that could be changed?

Kind regards,
Stefan
![SCR-20241021-mpfw](https://github.com/user-attachments/assets/db3af9dc-7382-4219-a0f9-6c48ae120e6f)
![SCR-20241021-mpmy](https://github.com/user-attachments/assets/6b0af314-eacd-4984-b958-402ddfe48d2a)

**Comment by jparkerweb** [comment]
addressed here:
https://github.com/jparkerweb/rich-foot/releases/tag/1.1.0
