### ISSUE TITLE
Bad foot position

### ISSUE THREAD

**Issue by SebastianAviles** [jparkerweb/rich-foot#8]
The footer show right instead button of note.

![image](https://github.com/user-attachments/assets/ea045919-dadf-4b91-ad0e-78efd387a8a7)

**Comment by jparkerweb** [comment]
Issue fixed!
update the plugin in Obsidian.

screenshot of test backlink page in `Source` mode:
![Image](https://github.com/user-attachments/assets/5c4c5d11-e3da-499c-9264-581c4f14cbcc)

**Comment by SebastianAviles** [comment]
Great! Solved!
