### ISSUE TITLE
[Feature-Request] Add Pagination to Periodic Notes

### ISSUE THREAD

**Issue by jpasholk** [jparkerweb/rich-foot#9]
Hey! 👋

Great plug-in, I'm glad that I found it.

I love the clean footer that it ads, but I wanted to make a feature request.

Would it be possibly to add in paginated links?

I'm using Templater to generate these, but it would look so much better if they were in the footer, maybe on the top right side similar to the "BACKLINKS" text.

![Screenshot](https://github.com/user-attachments/assets/8f3f651e-c317-49b2-8db7-1b92715fb58a)

I think this would be an awesome feature to add!

Either way, thanks for the great work!

**Comment by jparkerweb** [comment]
@jpasholk 
Neat idea, but unfortunately `Periodic Notes` isn't a `core plugin`. I would rather if Rich Foot didn't have any third-party plugin dependencies.  That being said, it might not be too difficult to write a quick `css snippet` that would place the pagination row below the dashed line, or even easier, at the bottom of the note all together.

Shoot me over the template file you use and I can try to take a look if you want some help with it.

**Comment by jpasholk** [comment]
That's a good idea!

I am using the [GitHub theme](https://github.com/krios2146/obsidian-theme-github).

I'd really appreciate the help with a css snippet. I know a bit of css, so I'll take a stab at it this weekend. 

Thanks!
